version: 1.10.4-dev+{build}
image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
branches:
  only:
    - master
    - appveyor-fixes
    - /\d*\.\d*\.\d*/

# note: on macOS the binary is built using Python 3.7 (installed via Homebrew), because
# the shipped Python lacks libraries PyInstaller needs.
stack: python 3.6

# note: 32 bit linux binary is build using docker
for:
-
  matrix:
    only:
      - image: Ubuntu

  services:
    - docker

environment:
  PY_DIR: C:\Python36-x64

init:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

build: off

artifacts:
  - path: "dist\\safety-win-i686.exe"
    name: "safety-win-i686.exe"
  - path: "dist\\safety-win-x86_64.exe"
    name: "safety-win-x86_64.exe"
  - path: "dist\\safety-linux-i686"
    name: "safety-linux-i686"
  - path: "dist\\safety-linux-x86_64"
    name: "safety-linux-x86_64"
  - path: "dist\\safety-macos-x86_64"
    name: "safety-macos-x86_64"

install:
  - "python --version"
  - "python appveyor.py install"

test_script:
  - "python appveyor.py test"
  - "python appveyor.py dist"


deploy:
  - provider: GitHub
    description: 'Safety Binary Release'
    auth_token:
      secure: h8S0XqdLIUQIPPshQfVy/ytDZ8lSD5o17RzabHGGXz2p68UNcxbSKtbu179TlI0C
    on:
      APPVEYOR_REPO_TAG: true
